// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "ir.quera.mattermost-rtl",
    "name": "Mattermost RTL",
    "description": "This plugin adds RTL support to Mattermost.",
    "version": "0.1.6",
    "min_server_version": "5.12.0",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
